/*
    Generator for the SMOKE sources
    Copyright (C) 2009 Arno Rehn <arno@arnorehn.de>

    This program is free software; you can redistribute it and/or modify
    it under the terms of the GNU General Public License as published by
    the Free Software Foundation; either version 2 of the License, or
    (at your option) any later version.

    This program is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
    GNU General Public License for more details.

    You should have received a copy of the GNU General Public License along
    with this program; if not, write to the Free Software Foundation, Inc.,
    51 Franklin Street, Fifth Floor, Boston, MA 02110-1301 USA.
*/

#include <QCoreApplication>
#include <QDir>
#include <QFile>
#include <QMap>
#include <QSet>
#include <QTextStream>

#include <type.h>

#include "globals.h"
#include "../../options.h"

SmokeClassFiles::SmokeClassFiles(SmokeDataFile *data)
    : m_smokeData(data)
{
}

void SmokeClassFiles::write()
{
    write(m_smokeData->includedClasses);
}

void SmokeClassFiles::write(const QList<QString>& keys)
{
    qDebug("writing out x_*.cpp [%s]", qPrintable(Options::module));
    
    // how many classes go in one file
    int count = keys.count() / Options::parts;
    int count2 = count;
    
    for (int i = 0; i < Options::parts; i++) {
        QSet<QString> includes;
        QString classCode;
        QTextStream classOut(&classCode);
        
        // write the class code to a QString so we can later prepend the #includes
        if (i == Options::parts - 1) count2 = -1;
        foreach (const QString& str, keys.mid(count * i, count2)) {
            const Class* klass = &classes[str];
            includes.insert(klass->fileName());
            writeClass(classOut, klass, str, includes);
        }
        
        // create the file
        QFile file(Options::outputDir.filePath("x_" + QString::number(i + 1) + ".cpp"));
        file.open(QFile::ReadWrite | QFile::Truncate);

        QTextStream fileOut(&file);
        
        // write out the header
        fileOut << "//Auto-generated by " << QCoreApplication::arguments()[0] << ". DO NOT EDIT.\n";
       
        // Adjustment by Open CASCADE, foreware inclusion of _smoke.h file, smokegen sometimes does not
        // include the files in the correct order, so manually include them in _smoke.h
        fileOut << "\n#include <smoke.h>\n#include <" << Options::module << "_smoke.h>\n";

        // ... and the #includes
        QList<QString> sortedIncludes = includes.values();
        std::sort(sortedIncludes.begin(), sortedIncludes.end());
        for (QString& str : sortedIncludes) {
            if (str.isEmpty())
                continue;
            if (str.startsWith("/builtins/"))
                str.remove(0, 10);
	    // windows problem
	    if (str.contains('\\'))
	      str.replace('\\', '/');
	    QStringList strlst = str.split('/');
	    // Avoid error: redefinition by inclusion of file.h
	    if (!Options::excludeIncFiles.contains(strlst.last()))
	      fileOut << "#include <" << str << ">\n";
        }
	
	// Use namespace?
	for (QString& str : Options::moduleNamespaces)
	  fileOut << "\nusing namespace " << str << ";\n";	

        fileOut << "\nclass __internal_SmokeClass {};\n";

        fileOut << "\nnamespace __smoke" << Options::module << " {\n\n";

        // now the class code
        fileOut << classCode;
        
        fileOut << "\n}\n";
        
        file.close();
    }
}

QString SmokeClassFiles::generateMethodBody(const QString& indent, const QString& className, const QString& smokeClassName, const Method& meth,
                                            int index, bool dynamicDispatch, QSet<QString>& includes,
                                            bool privateDestructor)
{
    QString methodBody;
    QTextStream out(&methodBody);
    bool paramArrRef = false;

    out << indent;

    if (meth.isConstructor()) {
        out << smokeClassName << "* xret = new " << smokeClassName << "(";
    } else {
        const Function* func = Util::globalFunctionMap[&meth];
        if (func)
            includes.insert(func->fileName());

        addIncludesForType(includes, meth.type());

        if (meth.type()->isFunctionPointer() || meth.type()->isArray())
            out << meth.type()->toString("xret") << " = ";
        else if (meth.type() != Type::Void) {
	  // className|meth.toString()|typeName|BadCast
	  bool found = false;
	  if (!Options::tripleConditions.isEmpty()) {
	    for (QString& str : Options::tripleConditions) {
	      QStringList strlst = str.split('|');
	      // Has field "BadCast"?
	      if (strlst.size() > 3) 
	      if (className.contains(strlst.at(0)) && meth.toString().contains(strlst.at(1)) && strlst.at(3).contains("BadCast")) {
		out << strlst.at(2) << " xret = ";
		found = true;
		break;
	      }
	    }
	  }
	  if (!found) {
	    QString typeName = meth.type()->toString();
	    // Reference to pointer?
	    if (typeName.contains("*&"))
	      typeName.replace("&", "");
	    out << typeName << " xret = ";
	  }
	}
        if (!(meth.flags() & Method::Static)) {
            QString objName = privateDestructor ? "obj" : "this";
            if (meth.isConst()) {
	      Options::OverridesFinalFunctions.contains(meth.name()) ? out << "((" : out << "((const ";
	      out << (privateDestructor ? className : smokeClassName) << QString("*)%1)->").arg(objName);
            } else {
                out << QString("%1->").arg(objName);
            }
        }
        if (!dynamicDispatch && !func) {
            // dynamic dispatch not wanted, call with 'this->Foo::method()'
            out << className << "::";
        } else if (func) {
	  if (!func->nameSpace().isEmpty()) {
	    bool condition = false;
	    for (QString& str : Options::doubleConditions) {
	      QStringList strlst = str.split('|');
	      if (meth.name().contains(strlst.at(0)) || meth.name().contains(strlst.at(1))) {
	    	condition = true;
		break;
	      }
	    }
	    if (!condition)
	      out << func->nameSpace() << "::";
	  }
        }
        out << meth.name() << "(";
    }

    for (int j = 0; j < meth.parameters().count(); j++) {
        const Parameter& param = meth.parameters()[j];

        addIncludesForType(includes, param.type());

        if (j > 0) out << ",";

        QString field = Util::stackItemField(param.type());
        QString typeName = param.type()->toString();
	if (param.type()->isArray()) {
	  Type t = *param.type();
	  t.setPointerDepth(t.pointerDepth() + 1);
	  t.setIsRef(false);
	  typeName = t.toString();
	  out << '*';
	} else if (field == "s_class" && (param.type()->pointerDepth() == 0 || param.type()->isRef()) && !param.type()->isFunctionPointer()) {
	  // pass an array by reference
	  if (param.type()->toString().remove(QRegularExpression(" ")).contains("]&")) {
	    QString str = param.type()->toString();
	    // double const
	    if (str.count("const") > 1)
	      str.remove(0, 6);
	    QStringList stl = str.split("[");
	    typeName = stl.at(0) + "(&)[" + stl.at(1).split("]").at(0) + "]";
	    // & bypass removal.
	    paramArrRef = true;
	  } else {
	    // references and classes are passed in s_class
	    typeName.append('*');
	    out << '*';
	  }
	}
	// Erroneous cast. Reference to pointer '&(*)' in function pointer.
	for (QString& str : Options::doubleConditions) {
	  QStringList strlst = str.split('|');
	  if (typeName.contains(strlst.at(1)) && meth.name().contains(strlst.at(0)))
	    typeName.replace("&", "");
	}
	// casting to a reference doesn't make sense in this case
	if (param.type()->isRef() && !param.type()->isFunctionPointer() && !paramArrRef) {
	  //Multiples '&' example "const std::function<void (const QWebEngineFindTextResult &)>&"
	  int pos = typeName.lastIndexOf('&');
	  typeName.replace(pos,1, ' ');
	}
	bool condition = false;
	// Reference to ‘identifier’ is ambiguous?
	for (QString& str : Options::tripleConditions) {
	  QStringList strlst = str.split('|');
	  // Bad cast in various parameters, find in smokeconfig.xml the 'cast' (OCCT).
	  // className|meth.toString()|typeName|idx_param
	  if (strlst.size() > 3) {
	    int idx_param = strlst.at(3).toInt();
	    if ((idx_param > 0) && (idx_param == (j+1)) && smokeClassName.contains(strlst.at(0)) && meth.name().contains(strlst.at(1))) {
	      out << "("  << strlst.at(2) << ")" << "x[" << j + 1 << "]." << field;
	      condition = true;
	    }
	  } else
	    if (smokeClassName.contains(strlst.at(0)) && (meth.name().contains(strlst.at(1)) || meth.name().contains(strlst.at(2)))) {
	      out << "(" << strlst.at(0) << "::" << typeName << ")" << "x[" << j + 1 << "]." << field;
	      condition = true;
	      break;
	    }
	}
	if (!condition)
	  out << "(" << typeName << ")" << "x[" << j + 1 << "]." << field;
    }// for

    // if the method is constructor and check if the constructor needs remaining default values
    bool aceptRemainingDefaultValues = true;
    if (meth.isConstructor()) {
      for (QString& str : Options::constructorDeniesRemainingDefaultValue) {
	if (meth.name().contains(str)) {
	  aceptRemainingDefaultValues = false;
	  break;
	}
      }
    }
    // if the method has any other default parameters, append them here as values     
    if (!meth.remainingDefaultValues().isEmpty() && aceptRemainingDefaultValues) {
      QStringList  defaultParams = QStringList(meth.remainingDefaultValues());
      QString substituted;
      //Avoid error : reference to type 'const ClassName' cannot bind to an initializer list
      for (int i = 0; i < defaultParams.size(); ++i) {
        if (defaultParams.at(i).contains("{}")) {
          substituted = defaultParams.at(i);
          defaultParams.replaceInStrings(substituted,"{}");
        }
      }
      if (meth.parameters().count() > 0)
        out << "," ;
      out << defaultParams.join(",");
    }

    out << ");\n";
    if (meth.type() != Type::Void) {
      auto field = Util::stackItemField(meth.type());
      if (field == "s_enum")
        out << indent << "x[0]." << field << " = " << Util::assignmentString(meth.type(), "xret") << ";\n";
      else {
	// className|meth.toString()|typeName|BadCast
	if (!Options::tripleConditions.isEmpty()) {
	  for (QString& str : Options::tripleConditions) {
	    QStringList strlst = str.split('|');
	    // Has field "BadCast"?
	    if (strlst.size() > 3) 
	    if (className.contains(strlst.at(0)) && meth.toString().contains(strlst.at(1)) && strlst.at(3).contains("BadCast")) {
	      out <<  indent << "x[0]." << field << " = " << "(void*)new " << strlst.at(2) << "(xret);\n";
	      return methodBody;
	    }
	  }
	}
	out << indent << "x[0]." << field << " = " << Util::assignmentString(meth.type(), "xret") << ";\n";
      }
    } else {
      out << indent << "(void)x; // noop (for compiler warning)\n";
    }
    return methodBody;
}

void SmokeClassFiles::generateMethod(QTextStream& out, const QString& className, const QString& smokeClassName,
                                     const Method& meth, int index, QSet<QString>& includes,
                                     bool privateDestructor)
{
    out << "    ";
    if ((meth.flags() & Method::Static) || meth.isConstructor() || privateDestructor)
        out << "static ";
    out << QString("void x_%1(%2Smoke::Stack x) {\n").arg(index)
        .arg((!(meth.flags() & Method::Static) && privateDestructor) ? (className + "* obj, ") : "");
    out << "        // " << meth.toString() << "\n";

    bool dynamicDispatch = ((meth.flags() & Method::PureVirtual) || (meth.flags() & Method::DynamicDispatch));

    if (dynamicDispatch || !Util::virtualMethodsForClass(meth.getClass()).contains(&meth)) {
        // This is either already flagged as dynamic dispatch or just a normal method. We can generate a normal method call for it.

        out << generateMethodBody("        ",   // indent
                                  className, smokeClassName, meth, index, dynamicDispatch, includes, privateDestructor);
    } else {
        // This is a virtual method. To know whether we should call with dynamic dispatch, we need a bit of RTTI magic.
        includes.insert("typeinfo");
        out << "        if (dynamic_cast<__internal_SmokeClass*>(static_cast<" << className << "*>(this))) {\n";   //
        out << generateMethodBody("            ",   // indent
                                  className, smokeClassName, meth, index, false, includes, privateDestructor);
        out << "        } else {\n";
        out << generateMethodBody("            ",   // indent
                                  className, smokeClassName, meth, index, true, includes, privateDestructor);
        out << "        }\n";
    }

    out << "    }\n";
    
    // If the constructor was generated from another one with default parameteres, we don't need to explicitly create
    // it here again. The x_* call will append the default parameters at the end and thus choose the right constructor.
    if (meth.isConstructor() && meth.remainingDefaultValues().isEmpty()) {
        out << "    explicit " << smokeClassName << '(';
        QStringList x_list;
        for (int i = 0; i < meth.parameters().count(); i++) {
            if (i > 0) out << ", ";
            QString param = meth.parameters()[i].type()->toString();
	    // Correctly make the function pointer in the parameter.
	    if (meth.parameters()[i].type()->isFunctionPointer())
	      out << param.replace("(*)","(*x" + QString::number(i + 1) + ")");
	    else {
	      // pass an array by reference
	      QString str = param;
	      if (str.remove(QRegularExpression(" ")).contains("]&")) {
		// double const
		if (param.count("const") > 1)
		  param.remove(0, 6);
		QStringList stl = param.split("[");
		out << stl.at(0) << "(&x" + QString::number(i + 1) << ")[" << stl.at(1).split("]").at(0) << "]";
	      } else
		out << param << " x" << QString::number(i + 1);
	    }
	    x_list << "x" + QString::number(i + 1);
	}
	out << ") : " << meth.getClass()->name() << '(' << x_list.join(", ") << ") {}\n";
    }
}

void SmokeClassFiles::generateGetAccessor(QTextStream& out, const QString& className, const Field& field,
                                          const Type* type, int index)
{
    out << "    ";
    QString fieldName;
    if (field.flags() & Field::Static) {
        out << "static ";
    } else {
        fieldName = "this->";
    }
    fieldName += className + "::" + field.name();
    out << "void x_" << index << "(Smoke::Stack x) {\n"
        << "        // " << field.toString() << "\n"
        << "        x[0]." << Util::stackItemField(type) << " = "
            << Util::assignmentString(type, fieldName) << ";\n"
        << "    }\n";
}

void SmokeClassFiles::generateSetAccessor(QTextStream& out, const QString& className, const Field& field,
                                          const Type* type, int index)
{
    out << "    ";
    QString fieldName;
    if (field.flags() & Field::Static) {
        out << "static ";
    } else {
        fieldName = "this->";
    }
    fieldName += className + "::" + field.name();
    out << "void x_" << index << "(Smoke::Stack x) {\n"
        << "        // " << field.toString() << "=\n";
    QString unionField = Util::stackItemField(type);
    
    // Converting a void* to a function pointer directly is not allowed.
    if (type->isFunctionPointer()) {
      out  << "        " << fieldName << " = " << "reinterpret_cast<" << type->toString()
	   << ">(reinterpret_cast<std::uintptr_t>(x[1]." << unionField + "));\n" << "    }\n";
	   return;
    }
    
    QString cast = type->toString();
    cast.replace("&", "");
    // Bad cast, posible bug in parser, find in smokeconfig.xml the 'cast' (OCCT).
    if (!Options::doubleConditions.isEmpty()) {
      for (QString& str : Options::doubleConditions) {
	QStringList strlst = str.split('|');
	if (strlst.at(0) == field.toString()) {
	  cast = strlst.at(1);
	  break;
	}
      }
    }
 
    // C++ haven't first class arrays.
    if (cast.contains("[") && (unionField == "s_class" && type->pointerDepth() == 0)) {
      QStringList strlst = field.toString().split('[');
      // Multi-dimensional Arrays
      int siz = 1;
      for (int i = 0; i < strlst.size()-1; i++) {
	QStringList list = strlst.at(i+1).split("]");
	siz = siz * list.at(0).toInt();
      }
      out << "        " << "std::memcpy(" << fieldName << ", x[1].s_class, " << siz
	  << "*sizeof(" <<  strlst.at(0) << "));\n" << "    }\n";
      return;
    }

    // operator= is private within this context or delete, use std::memcpy instead (OCCT).
    if (!Options::doubleConditions.isEmpty() && (unionField == "s_class" && type->pointerDepth() == 0)) {
      for (QString& str : Options::doubleConditions) {
	QStringList strlst = str.split('|');
	if (className == strlst.at(0) && field.toString() == strlst.at(1)) {
	  out << "        " << "std::memcpy(&" << fieldName << ", "
	      << "(" << cast << "*)x[1].s_class, sizeof(" << className << "));\n    }\n";
	  return;
	}
      }
    }

    // an array of pointers
    if (cast.contains("(*)[")) {
      QStringList strlst = cast.split('[');
      out << "        " << "std::memcpy(" << fieldName << ", x[1].s_class, " << "sizeof("
	  << strlst.at(0) << ")*" << strlst.at(1).split(']').at(0) << ");\n" << "    }\n";
      return;
    }

    out << "        " << fieldName << " = ";
    if (unionField == "s_class" && type->pointerDepth() == 0) {
      out << "*";
      cast += '*';
    }
    out << '(' << cast << ')' << "x[1]." << unionField << ";\n";
    out << "    }\n";
}

void SmokeClassFiles::generateEnumMemberCall(QTextStream& out, const QString& parentName, const QString& className, bool isScoped, const QString& member, int index)
{
    out << "    static void x_" << index << "(Smoke::Stack x) {\n"
        << "        x[0].s_enum = static_cast<long>(";
    
    if (!parentName.isEmpty()) {
        out << parentName << "::";
    }
    if (isScoped) {
        out << className << "::";
    }
    
    out << member << ");\n"
        << "    }\n";
}

void SmokeClassFiles::generateVirtualMethod(QTextStream& out, const Method& meth, QSet<QString>& includes)
{
    QString x_params, x_list;
    QString type = meth.type()->toString();
    addIncludesForType(includes, meth.type());
    
    out << "    virtual " << type << " " << meth.name() << "(";
    for (int i = 0; i < meth.parameters().count(); i++) {
        if (i > 0) { out << ", "; x_list.append(", "); }
        const Parameter& param = meth.parameters()[i];
        
        addIncludesForType(includes, param.type());
        
        out << param.type()->toString() << " x" << i + 1;
        x_params += QString("        x[%1].%2 = %3;\n")
            .arg(QString::number(i + 1)).arg(Util::stackItemField(param.type()))
            .arg(Util::assignmentString(param.type(), "x" + QString::number(i + 1)));
        x_list += "x" + QString::number(i + 1);
    }
    out << ") ";
    if (meth.isConst())
      if (!Options::OverridesFinalFunctions.contains(meth.name()))
	out << "const ";
    if (meth.hasExceptionSpec()) {
        out << "throw(";
        for (int i = 0; i < meth.exceptionTypes().count(); i++) {
            if (i > 0) out << ", ";
            out << meth.exceptionTypes()[i].toString();
        }
        out << ") ";
    }
    out << "{\n";
    out << QString("        Smoke::StackItem x[%1];\n").arg(meth.parameters().count() + 1);
    out << x_params;
    
    if (meth.flags() & Method::PureVirtual) {
        out << QString("        this->_binding->callMethod(%1, (void*)this, x, true /*pure virtual*/);\n").arg(m_smokeData->methodIdx[&meth]);
        if (meth.type() != Type::Void) {
            QString field = Util::stackItemField(meth.type());
            if (meth.type()->pointerDepth() == 0 && field == "s_class") {
                QString tmpType = type;
                if (meth.type()->isRef()) tmpType.replace('&', "");
                tmpType.append('*');
                out << "        " << tmpType << " xptr = (" << tmpType << ")x[0].s_class;\n";
                out << "        " << type << " xret(*xptr);\n";
                out << "        delete xptr;\n";
                out << "        return xret;\n";
            } else {
                out << QString("        return (%1)x[0].%2;\n").arg(type, Util::stackItemField(meth.type()));
            }
        }
    } else {
        out << QString("        if (this->_binding->callMethod(%1, (void*)this, x)) ").arg(m_smokeData->methodIdx[&meth]);
        if (meth.type() == Type::Void) {
            out << "return;\n";
        } else {
            QString field = Util::stackItemField(meth.type());
            if (meth.type()->pointerDepth() == 0 && field == "s_class") {
                QString tmpType = type;
                if (meth.type()->isRef()) tmpType.replace('&', "");
                tmpType.append('*');
                out << "{\n";
                out << "            " << tmpType << " xptr = (" << tmpType << ")x[0].s_class;\n";
                out << "            " << type << " xret(*xptr);\n";
                out << "            delete xptr;\n";
                out << "            return xret;\n";
                out << "        }\n";
            } else {
                out << QString("return (%1)x[0].%2;\n").arg(type, Util::stackItemField(meth.type()));
            }
        }
        out << "        ";
        if (meth.type() != Type::Void)
            out << "return ";
        out << QString("this->%1::%2(%3);\n").arg(meth.getClass()->toString()).arg(meth.name()).arg(x_list);
    }
    out << "    }\n";
}

void SmokeClassFiles::writeClass(QTextStream& out, const Class* klass, const QString& className, QSet<QString>& includes)
{
    // Find the destructor.  If the destructor is private, then we can't
    // subclass from this class.  All calls in the x_Class must be static, and
    // the class won't inherit from anything.
    const Method *destructor = Util::findDestructor(klass);
    bool privateDestructor = destructor ? (destructor->access() == Access_private) : false;

    const QString underscoreName = QString(className).replace("::", "__");
    const QString smokeClassName = "x_" + underscoreName;

    QString switchCode;
    QTextStream switchOut(&switchCode);

    out << QString("class %1").arg(smokeClassName);
    if (!klass->isNameSpace()) {
        if (!privateDestructor) {
            out << QString(" : public %1").arg(className);
            if (Util::hasClassVirtualDestructor(klass) && Util::hasClassPublicDestructor(klass)) {
                out << ", public __internal_SmokeClass";
            }
        }
    }
    out << " {\n";
    if (Util::canClassBeInstanciated(klass)) {
        out << "    SmokeBinding* _binding;\n";
        out << "public:\n";
        out << "    void x_0(Smoke::Stack x) {\n";
        out << "        // set the smoke binding\n";
        out << "        _binding = (SmokeBinding*)x[1].s_class;\n";
        out << "    }\n";
        
        for (QString& str : Options::needOpNew) {
	  if (str.contains(className))
	    out << "    static void* operator new(std::size_t siz) {  return ::operator new(siz); }\n";
        }
              
        switchOut << "        case 0: xself->x_0(args);\tbreak;\n";
    } else {
        out << "public:\n";
    }
    
    int xcall_index = 1;

    foreach (const Method& meth, klass->methods()) {
        if (&meth == destructor)
            continue;

        if (meth.access() == Access_private)
            continue;

        QString obj;
        if ((meth.flags() & Method::Static) || meth.isConstructor() || privateDestructor)
            obj = smokeClassName + "::";
        else
            obj = "xself->";

        switchOut << "        case " << xcall_index << ": "
                  << obj
                  << "x_" << xcall_index << QString("(%1args);\tbreak;\n")
                     .arg((!(meth.flags() & Method::Static) && privateDestructor) ? "xself, " : "");
        if (Util::fieldAccessors.contains(&meth)) {
            // accessor method?
            const Field* field = Util::fieldAccessors[&meth];
            if (meth.name().startsWith("set")) {
                generateSetAccessor(out, className, *field, meth.parameters()[0].type(), xcall_index);
            } else {
                generateGetAccessor(out, className, *field, meth.type(), xcall_index);
            }
        } else {
            generateMethod(out, className, smokeClassName, meth, xcall_index, includes, privateDestructor);
        }
        xcall_index++;
    }

    QString enumCode;
    QTextStream enumOut(&enumCode);
    const Enum* e = 0;
    bool enumFound = false;
    foreach (const BasicTypeDeclaration* decl, klass->children()) {
        if (!(e = dynamic_cast<const Enum*>(decl)))
            continue;
        if (e->access() == Access_private)
            continue;
        
        foreach (const EnumMember& member, e->members()) {
            switchOut << "        case " << xcall_index << ": " << smokeClassName <<  "::x_" << xcall_index << "(args);\tbreak;\n";
            if (e->parent())
                generateEnumMemberCall(out, className, e->name(), e->isScoped(), member.name(), xcall_index++);
            else
                generateEnumMemberCall(out, e->nameSpace(), e->name(), e->isScoped(), member.name(), xcall_index++);
        }
        
        // only generate the xenum_call if the enum has a valid name
        if (e->name().isEmpty())
            continue;
        
        enumFound = true;
        
        // xenum_operation method code
        QString enumString = e->toString();
        enumOut << "        case " << m_smokeData->typeIndex[&types[enumString]] << ": //" << enumString << '\n';
        enumOut << "            switch(xop) {\n";
        enumOut << "                case Smoke::EnumNew:\n";
        enumOut << "                    xdata = (void*)new " << enumString << ";\n";
        enumOut << "                    break;\n";
        enumOut << "                case Smoke::EnumDelete:\n";
        enumOut << "                    delete (" << enumString << "*)xdata;\n";
        enumOut << "                    break;\n";
        enumOut << "                case Smoke::EnumFromLong:\n";
        enumOut << "                    *(" << enumString << "*)xdata = (" << enumString << ")xvalue;\n";
        enumOut << "                    break;\n";
        enumOut << "                case Smoke::EnumToLong:\n";
        enumOut << "                    xvalue = (long)*(" << enumString << "*)xdata;\n";
        enumOut << "                    break;\n";
        enumOut << "            }\n";
        enumOut << "            break;\n";
    }
    
    foreach (const Method* meth, Util::virtualMethodsForClass(klass)) {
        generateVirtualMethod(out, *meth, includes);
    }
    
    // this class contains enums, write out an xenum_operation method
    if (enumFound) {
        out << "    static void xenum_operation(Smoke::EnumOperation xop, Smoke::Index xtype, void *&xdata, long &xvalue) {\n";
        out << "        switch(xtype) {\n";
        out << enumCode;
        out << "        }\n";
        out << "    }\n";
    }
    
    // destructor
    // if the class can't be instanstiated, a callback when it's deleted is unnecessary
    if (Util::canClassBeInstanciated(klass)) {
        out << "    ~" << smokeClassName << "() ";
        if (destructor && destructor->hasExceptionSpec()) {
            out << "throw(";
            for (int i = 0; i < destructor->exceptionTypes().count(); i++) {
                if (i > 0) out << ", ";
                out << destructor->exceptionTypes()[i].toString();
            }
            out << ") ";
        }
        out << QString("{ this->_binding->deleted(%1, (void*)this); }\n").arg(m_smokeData->classIndex[className]);
    }
    out << "};\n";
    
    if (enumFound) {
        out << "void xenum_" << underscoreName << "(Smoke::EnumOperation xop, Smoke::Index xtype, void *&xdata, long &xvalue) {\n";
        out << "    " << smokeClassName << "::xenum_operation(xop, xtype, xdata, xvalue);\n";
        out << "}\n";
    }
    
    // xcall_class function
    out << "void xcall_" << underscoreName << "(Smoke::Index xi, void *obj, Smoke::Stack args) {\n";
    if (privateDestructor)
        out << "    " << className << " *xself = (" << className << "*)obj;\n";
    else
        out << "    " << smokeClassName << " *xself = (" << smokeClassName << "*)obj;\n";
    out << "    switch(xi) {\n";
    out << switchCode;
    if (Util::hasClassPublicDestructor(klass))
        out << "        case " << xcall_index << ": delete (" << className << "*)xself;\tbreak;\n";
    out << "    }\n";
    out << "}\n";
}

void SmokeClassFiles::addIncludesForType(QSet< QString >& includes, const Type* type) {
    if (type->getClass()) {
        includes.insert(type->getClass()->fileName());
    }

    for (int i = 0; i < type->templateArguments().size(); i++) {
        addIncludesForType(includes, &type->templateArguments()[i]);
    }
}
